<a href="https://colab.research.google.com/github/James334969/class05/blob/main/%E7%89%A9%E4%BB%B6%E5%B0%8E%E5%90%914.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Person:
    #建構子(costructer)
    def  __init__(self,name,gender):
        self.n = name
        self.g = gender
        print("This is Person Class")

    #method
    def introduction(self):
        print(f"Hi, my name is {self.n}")    
#物件化(實體化)
p1 = Person(name="James",gender="male")
p2 = Person(name="Amy",gender="female")
print(p1.n,p1.g)
print(p2.n,p2.g)

p1.introduction()
p2.introduction()
   

This is Person Class
This is Person Class
James male
Amy female
Hi, my name is James
Hi, my name is Amy


In [ ]:
class Enemy:
    def __init__(self):
        self.name = "monster"
        self.hp = 100
e = Enemy()
class Worrier:
    def __init__(self,name,gender,weapon = "bat"):
        self.lv = 1
        self.exp = 0
        self.n = name
        self.g = gender
        self.w = weapon
        print("This is Worrier class")
    def __str__(self):
        return f"name:{self.n},gender:{self.g},weapon:{self.w},exp:{self.exp},lv:{self.lv}"
    def attack(self,enemy):
        enemy.hp-=1
        self.exp+=40
        self.level_up()
        print(f"{self.n} attack!")
        print(f"{self.n} lv={self.lv}, exp={self.exp}")
        print(f"{enemy.name} hp={enemy.hp}")
    def level_up(self):
        if self.exp >= 100:
            self.lv+=1
            self.exp-=100
            print("Level Up!!")
w1 = Worrier(name="James",gender="male",weapon="sword")
w2 = Worrier(name="Allie",gender="female",weapon="longbow")
print(f"worrier:{w1}")
#print(w1)
for i in range(3):
    w1.attack(enemy=e)

This is Worrier class
This is Worrier class
worrier:name:James,gender:male,weapon:sword,exp:0,lv:1
James attack!
James lv=1, exp=40
monster hp=99
James attack!
James lv=1, exp=80
monster hp=98
Level Up!!
James attack!
James lv=2, exp=20
monster hp=97


In [ ]:
class Enemy:
    def __init__(self):
        self.name = "monster"
        self.hp = 100
#物件化
e = Enemy()
class Character:
    def __init__(self,name,gender,weapon = "bat"):
        self.lv = 1
        self.exp = 0
        self.n = name
        self.g = gender
        self.w = weapon
        print("This is Character class")
    def __str__(self):
        return f"name:{self.n},gender:{self.g},weapon:{self.w},exp:{self.exp},lv:{self.lv}"
    def attack(self,enemy):
        enemy.hp-=1
        self.exp+=40
        self.level_up()
        print(f"{self.n} attack!")
        print(f"{self.n} lv={self.lv}, exp={self.exp}")
        print(f"{enemy.name} hp={enemy.hp}")
    def level_up(self):
        if self.exp >= 100:
            self.lv+=1
            self.exp-=100
            print("Level Up!!")
class Magician(Character):
    def __init__(self,name,gender,weapon = "bat"):
        super().__init__(name,gender,weapon)
        self.sp = 100
class Worrier(Character):
    def __init__(self,name,gender,weapon = "bat"):
        super().__init__(name,gender,weapon)
        self.sp = 100
w1 = Worrier(name="james",gender="male",weapon="sword")
print(w1)
for i in range(5):
    w1.attack(enemy = e)

This is Character class
name:james,gender:male,weapon:sword,exp:0,lv:1
james attack!
james lv=1, exp=40
monster hp=99
james attack!
james lv=1, exp=80
monster hp=98
Level Up!!
james attack!
james lv=2, exp=20
monster hp=97
james attack!
james lv=2, exp=60
monster hp=96
Level Up!!
james attack!
james lv=3, exp=0
monster hp=95


#**numpy**

In [ ]:
import numpy as np
a = [1,2,3]
b = [4,5,6]
arr1 = np.array(a)
arr2 = np.array(b)
print(arr1+arr2)

[5 7 9]


In [ ]:
a = np.array([1,2,3])
b = np.array([[1.0,2.0,3.0],[3.2,5.7,8.2]])
print(f"a: {a}")
print(f"a dimension: {a.ndim}")
print(f"a shape: {a.shape}")
print(f"a type: {a.dtype}")
print(f"b: {b}")
print(f"b dimension: {b.ndim}")
print(f"b shape: {b.shape}")
print(f"b type: {b.dtype}")

a: [1 2 3]
a dimension: 1
a shape: (3,)
a type: int64
b: [[1.  2.  3. ]
 [3.2 5.7 8.2]]
b dimension: 2
b shape: (2, 3)
b type: float64


In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a[1,2])
print(a[0,:])

9
[1 2 3 4 5 6]


In [ ]:
a = np.array([[[1,2],[3,5],[7,8]],
              [[1,7],[-3,2],[10,2]],
              [[6,-2],[5,-3],[7,9]],
              [[8,5],[-2,2],[26,-2]],
              [[1,-7],[-3,2],[-5,-2]],])
print(a)
print(a.shape) 
print(a[3,2,0])
print(a[:,1,:])

[[[ 1  2]
  [ 3  5]
  [ 7  8]]

 [[ 1  7]
  [-3  2]
  [10  2]]

 [[ 6 -2]
  [ 5 -3]
  [ 7  9]]

 [[ 8  5]
  [-2  2]
  [26 -2]]

 [[ 1 -7]
  [-3  2]
  [-5 -2]]]
(5, 3, 2)
26
[[ 3  5]
 [-3  2]
 [ 5 -3]
 [-2  2]
 [-3  2]]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[2,3,1],[5,2,1]])
print(np.matmul(a,b))

[[12  7  3]
 [26 17  7]
 [40 27 11]]
